export const APP_VERSION = '6.0.3-beta.8-p7-hf2';
export const APP_VERSION_LABEL = `v${APP_VERSION}`;
export const APP_CHECKPOINT_ID = 'V6.0.3-BETA8-P7-HF2-GLOBAL-PLAYER-DEFAULTS';
export const APP_CHECKPOINT_LABEL = 'V6.0.3 beta.8 P7 HF2 • Global Player + Voice Defaults Alignment';
export const APP_RELEASE_NAME = 'beta.8 P7 HF2 Global Player + Voice Defaults Alignment';
export const APP_RELEASE_DATE = '2026-09-20';

export const APP_READY_LOG = `Ready. ProLingo ${APP_VERSION_LABEL} (${APP_RELEASE_NAME}).`;
export const APP_DATA_MANAGER_RELEASE_NOTE = `${APP_VERSION_LABEL}: P7 HF2 closes the remaining beta.8 global-player contract gaps on top of boot-safe HF1: Split remains the default global representation, EN/ID local playback priority is truly app-global across Documents, TTS Only has one global source of truth, bottom Global Player exposes Split/Full + TTS state + effective voice order, normal/manual Edge defaults are Sonia EN and Tuti ID, Browser EN prefers UK Female, while Bulk EN remains Libby. Text DB remains v1 and Table is untouched.`;
export const APP_MANUAL_EDITOR_RELEASE_LABEL = `${APP_VERSION_LABEL} • SENTENCE-AUTHORING`;

export const APP_CHANGELOG = Object.freeze([
  'v6.0.3-beta.8-p7-hf2 aligns the frozen beta.8 global-player contract on top of boot-safe HF1: Structured Text local playback order is persisted globally across Documents with Card override > Global > legacy Document fallback precedence, TTS Only uses the global audio-source preference instead of per-Document state, Split/Full and local/TTS state plus EN/ID order are visible in the bottom Global Player, Browser EN prefers a UK female voice, normal/manual Edge defaults to Sonia EN + Tuti ID, and Bulk generation/export keeps Libby EN independently; Text DB stays v1 and Table/Conversation are untouched',
  'v6.0.3-beta.8-p7-hf1 fixes the runtime blank-screen regression inherited from P3 by removing the pre-declaration forceStopAll dependency from the playback-representation callback, restores the P7 Card Audio cardChannelCoverage derivation that was accidentally removed during UI simplification, and adds an explicit runtime-boot guard audit; no P1-P7 domain behavior, Text DB schema, or Table code is intentionally changed',
  'v6.0.3-beta.8-p7 completes beta.8 Paragraph UI simplification: Player Settings now exposes the already-implemented global Split / Full representation, TTS Only bypass, and explicit Workspace EN/ID local playback order; Card headers show compact Ready/Missing state, Card Audio keeps quick Generate Missing plus Advanced regeneration while scope exports are centralized in Bulk Audio, Bulk labels are phase-neutral Generate / Export, and duplicated legacy Split MP3/consolidated export controls are removed from the normal workflow without changing playback/generation/export domain contracts',
  'v6.0.3-beta.8-p6 adds Paragraph Bulk Export / Auto Export: Ready current-profile Split and Full binaries are selected from canonical IndexedDB Staging, Audio-Only supports human-readable direct files or ZIP, Portable ProLingo ZIP remains machine-reimportable with manifest + AUDIO_INDEX.csv, Preferred / Selected / All-selected voice policies and Split / Full / Both do not mutate playback order, physical identities are exported once even when shared by many logical consumers, stale text/profile artifacts fail closed, and Auto Export remains OFF by default and waits for durable Staging reconciliation',
  'v6.0.3-beta.8-p5 adds Paragraph-first Bulk Multi-Voice generation: one or many EN/ID voices can generate Split, Full, or Both into IndexedDB Staging; Generate Missing reuses exact physical RF/Full identities without unnecessary TTS, optional Missing + Stale refresh is separate, Shared RF and identical Full physical identities fan out across logical consumers, generation selection stays independent from playback priority, and telemetry separates logical requirements from unique/generated/reused physical binaries; Auto Export remains out of P5',
  'v6.0.3-beta.8-p4 completes Staging-first Portable ZIP: Split and Full physical audio converge into Text IndexedDB Staging, manifest v2 and AUDIO_INDEX.csv represent Split/Full identities, multi-ZIP imports merge additively across voices, Full Artifact binaries hydrate from Staging on startup, Staging GC understands Split and Full physical identity, and legacy Folder workflow is Deprecated/Locked without changing Text DB v1',
  'v6.0.3-beta.8-p3 adds persisted Split/Full runtime playback: Split remains default with per-Segment local/TTS hybrid plus EN/ID alignment, Full Ready plays directly, Full missing falls back through ordered Split with per-piece TTS and finally Full Browser TTS when no useful local Split route exists, TTS Only bypasses local audio without deletion, and manual one-Segment play keeps Split semantics',
  'v6.0.3-beta.8-p2 adds the frozen Split/Full domain: ordered canonical Segments deterministically derive Full EN/ID text, Full Audio uses an independent profile-aware full-sha256 artifact identity stored additively on Card metadata, Split and Full readiness are modeled independently, partial Split coverage remains valid, Segment content changes make old Full artifacts stale automatically, and deleting Split audio never deletes Full artifacts (or vice versa); Text DB remains v1',
  'v6.0.3-beta.8-p1 starts the frozen beta.8 contract with an additive Ordered Multi-Audio domain: Workspace playback profile order, Advanced Card override inheritance, first-READY local resolution with next-profile promotion, optional Workspace TTS-only policy, and strict separation between generation/download voice selection and playback priority; beta.7 Shared RF consumer sync remains intact and Text DB schema stays v1',
  'v6.0.3-beta.7 fixes Shared RF logical-consumer synchronization: Card/Bulk deferred generation now auto-links all matching Segment/channel slots, Staging/Folder/ZIP reuse fans out consistently, and manually releasing one shared staged RF updates every logical consumer instead of leaving sibling slots falsely Ready',
  'v6.0.3-beta.6 fixes the reproducible Shared-RF/Audio-Folder refresh crash by removing automatic startup folder scans, bulk-reconciling RF matches in one IndexedDB transaction, auto-linking sibling logical slots after one physical render is generated, and reporting physical RF files separately from logical matches; full RF SHA-256 remains the internal identity',
  'v6.0.3-beta.5 fixes Folder/ZIP exact-RF reuse during generation, adds async playback session guards, confirms destructive Staging/ZIP clears, clarifies Workspace/Collection/Text Pack cleanup semantics, collapses Card Generate & Export workflow, and renames scope-level Batch Audio to Bulk Audio with Retry Failed wiring for structured runtime testing',
  'v6.0.3-beta.4 hardens the beta.3 Data/Audio foundation for runtime acceptance: DATA/TRANSFER shows explicit external-source change counts and conflict choices, Runtime & Storage Diagnostics exposes DB/RF/Folder/ZIP state plus safe reference-derived Staging GC/reconnect, and Card Audio is reorganized into Prepare Audio → Split Download → Full Derived Audio with Selected Sentence helpers',
  'v6.0.3-beta.3 completes the frozen Data/Audio foundation through D3-D4, A0-A4, DL1-DL2 and B1: canonical external fingerprints/reconciliation, RF-centric shared physical audio, manifest-first cross-browser Folder/ZIP reconnect, reference-derived Text Staging GC, selected/full split downloads, derived Full Card WAV, and Batch physical-RF dedup while keeping Table frozen and Text DB/schema v1',
  'v6.0.3-beta.1 implements D0/D1 of the frozen Data+Audio contract: additive globally portable UIDs for Collection/Workspace/Card/Segment/Speaker/AudioVariant, one-time persistent backfill for existing Text data, UID-preserving ProLingo Attach/Sync, new-UID Import as Copy, and a contract regression harness while retaining Text DB/schema v1 and all legacy local IDs as IndexedDB keys',
  'v6.0.2-C-HF2 replaces atomic sentence buttons with naturally wrapping inline sentence targets, so a sentence can continue across lines without forced line breaks; Paragraph text uses inter-word justification with a normal left-aligned final line while active playback highlighting follows every wrapped fragment of the current sentence',
  'v6.0.2-C-HF1 refines Split Mode presentation: Paragraph layout remains visually identical to normal mode, sentence click targets have no persistent boxes/borders/padding, and only the currently playing sentence receives a temporary colour highlight',
  'v6.0.2-C keeps Paragraph content visually unified while optional Split Mode renders the same stable sentence Segments inline as clickable Segment-only playback boxes with active-sentence highlighting; detailed sentence audio controls remain available behind an explicit disclosure and no Text DB/schema contract changes',
  'v6.0.2-B exposes the accepted Paragraph Sentence foundation in the Card editor with preview-safe Auto Split, cursor-based Split Here, adjacent Merge, and explicit stable-ID Reorder controls without changing Text DB schema v1',
  'v6.0.2-A adds the Paragraph Sentence Authoring foundation: conservative sentence-split proposals, strict EN/ID alignment checks, stable-ID split/merge mutation commands, existing reorder reuse, and explicit stale-audio invalidation without a Text DB schema migration',
  'v6.0.1 cleans the Text DATA workspace without changing data contracts: Card/Segment editing is visible only in LIBRARY, redundant mode summary cards are removed, Manage no longer repeats an impossible active-Collection delete action, and Workspace terminology is clarified',
  'v6.0.0 promotes the user-accepted W1–W6 Workspace/Data redesign to the major-version release identity without changing the accepted runtime architecture',
  'The v6 promotion preserves Text IndexedDB/schema v1, permanent Collection/Document/Block/Segment identities, Text Pack v1 and Text DB Backup v1 compatibility, and the frozen Table core',
  'W6-RC aligns release metadata with the user-accepted W1–W5 source state and opens the final regression gate before any major-version promotion',
  'Workspace/Data redesign keeps IndexedDB v1 and existing Document/Block/Segment permanent identities: UI Workspace maps to Document, Book Collection remains optional, and JSON v1 wire terminology remains unchanged',
  'Paragraph Cards support TITLE/PARAGRAPH roles on existing metadata and existing stable Segments serve as sentence identities with scope-preserving Segment/Card/Start From Here/Workspace playback',
  'Conversation MIX reuses structured mixed Documents with Workspace speakerRegistryV1 and stable SPK_* identities; Paragraph narrator and Conversation speaker behavior remain segment-driven',
  'Audio Download uses DEFAULT/FOLLOW PLAYER/CUSTOM inheritance and Text Batch is Book Collection-first with explicit Current Card/Workspace/Selected/All scopes while reusing the same resolved download voice contract',
  'W6 regression preserves Text Pack v1, Text DB Backup v1, folder audio identity reconnect, Legacy compatibility, Unfiled Workspaces, and the frozen Table core',
  'T16B-HF1 fixes a data-dependent Text blank screen: TextStructuredPlayer now declares manual Segment/Card playback channel modes before card playability is evaluated, eliminating the runtime temporal-dead-zone failure that only appeared when structured Cards were present',
  'No Text DB/schema migration or demo-data lifecycle behavior is changed in T16B-HF1; Starter Demo persistence must be re-tested on the same normal browser origin after this runtime fix because private browsing intentionally uses separate storage',
  'Final Text T16B keeps AUDIO → DOWNLOAD untouched and refines only AUDIO → PLAYBACK plus body/player manual-play UX',
  'Conversation sync follower notes move below the fixed-size voice/speed controls so enabling Sync no longer changes individual control-box height; follower values remain non-destructive and restore when Sync is OFF',
  'Each detected Conversation speaker now has an expandable LOCAL READY inventory showing linked EN/ID local voices per Segment, while CUSTOM continues to select a preferred local voice with the selected TTS voice as fallback',
  'Player Settings adds a separate Manual Play section for Segment Only and Card Play with EN / ID / EN→ID / ID→EN plus Once / 2× / Custom count / Loop',
  'Segment Only uses Manual Play settings and becomes a Stop button while that exact Segment-only session is active; Card Play remains a one-shot Play action and Pause/Stop remains on the bottom player',
  'Expanded Segment cards always show compact EN/ID audio availability badges (Ready / History / Other / Stale / Missing) so downloaded/local coverage is visible without opening Segment Audio tools',
  'Final Text T16A replaces ambiguous LOAD ALL / CUSTOM / GLOBAL TTS playback choices with Local Audio ON/OFF plus AUTO/CUSTOM while keeping Folder/ZIP/Staging attachment under AUDIO → DOWNLOAD/SOURCES',
  'Conversation Sync Voice/Speed is now ON/OFF and non-destructive: follower speaker settings are locked to Speaker 1 at runtime without overwriting their saved voice, speed, or custom-local choices; turning Sync OFF restores those saved values',
  'Playback Audio now reports the actual source used by the latest channel as LOCAL (Folder/ZIP/Staging/Generated) or Browser TTS, including the effective voice and Speaker-1 sync state',
  'Final Text T15 fixes a runtime blank-screen regression introduced by T14: TextStructuredAudioControls no longer declares useState after a conditional return, preserving React hook order when Text hydration changes from no structured document to an active structured document',
  'T15 is forward-only over v5.14.13: no rollback, schema change, data migration, Table core change, audio identity change, Batch contract change or JSON lifecycle change is introduced',
  'Final Text T14 is a UX-only preflight over the sealed T13 architecture: Text Control Center is simplified to AUDIO / DATA / SYSTEM while Player Settings remains exclusively in the bottom player bar',
  'Text AUDIO is split into PLAYBACK and DOWNLOAD sub-surfaces so multi-speaker voice/speed controls no longer share one long scroll with Edge defaults, Staging, Folder and ZIP resources',
  'Text DATA labels are clarified to DATA WORKSPACE and explicitly describe Library / JSON / CRUD / Backup plus Batch launch; no audio resources are moved back into DATA',
  'Mobile bottom player labels the structured Text shortcut PLAYER instead of generic Settings, reducing ambiguity with AUDIO and DATA controls',
  'T14 changes navigation labels and presentation only; Text DB/schema, audio identity, runtime resolver, download inheritance, Batch scope, JSON lifecycle and frozen Table core remain unchanged',
  'Final Text T13 corrects the pre-runtime control architecture before device acceptance: bottom Player Settings owns playback behaviour only while sidebar AUDIO owns voice/speed/local-audio/download-resource configuration',
  'Mobile Table Study Queue restores Add Queue behind an expandable Study anchor without changing frozen src/components/table core files',
  'Conversation AUDIO profiles are derived from detected Segment speakers and expose independent EN/ID TTS voice + speed rows with sync-to-first-speaker controls; Paragraph remains one narrator EN+ID and Legacy remains EN-only',
  'Structured local audio now has explicit Load All / Custom / Global TTS modes; Custom resolves only the chosen available local voice per speaker/channel and otherwise falls back to Browser TTS instead of silently selecting another generated voice',
  'DATA no longer owns Text Folder/ZIP/Staging audio resources; those controls live under AUDIO while manual Generate/MP3 stays on Card/Segment Audio and mass generation stays in Batch',
  'Text Batch scope expands from active-Document range to Active Document / Current Collection / Selected Documents / All Structured Documents while every job carries document identity',
  'Multi-Document Batch coverage and generation preserve each Document/speaker/channel download inheritance and consolidated ZIP output is split back into separate Document archives',
  'Runtime-FROZEN is still intentionally pending real desktop/mobile acceptance on the sealed T13 Full Release Candidate',
  'Final Text T12 separates Player playback configuration from Text Audio/Download generation/export configuration before runtime acceptance',
  'Structured Text playback now has independent EN/Text and ID/Meaning speed with optional SYNC while legacy browserTtsRate preferences migrate compatibly',
  'Conversation Player profiles remain segment-driven: every stable speaker found in the active Document receives independent EN/ID playback voice controls',
  'Mobile Text adds direct Document switching plus DATA access in the study surface; mobile bottom player exposes separate PLAYER and AUDIO shortcuts',
  'Text Library replaces the primary Document dropdown workflow with All/Legacy/Paragraph/Conversation tabs, a unified filtered list, and starter demos',
  'Mobile Table Add Queue range returns beside the learning body instead of remaining buried in Data settings; Table core components remain untouched',
  'Text Batch explicitly follows Text Audio / Edge Download profiles and remains independent from Player voices and Player playback speed',
  'Final Text T11 consolidates the new authoritative C0–C14 regression gate and replaces obsolete version-pinned P4/R2 tests as the release decision surface',
  'C14 verifies full Table-critical byte freeze against v5.13.10, Text DB/schema v1 migration safety, the three official Text modes, source lifecycle, multi-speaker audio, manual audio, Batch resume/export/resource guards, canonical naming, Player relocation, and mobile parity',
  'Synthetic 5,000-Card / 10,000-job Text Batch planning stress completes with metadata-only jobs and no Blob/ObjectURL payload retention in the batch plan',
  'Historical P4/R2 tests that pin superseded versions/checkpoints remain archived as compatibility evidence and are not used to force modern Final Text behavior backward',
  'Engineering final is complete; runtime freeze remains gated on the combined desktop/mobile acceptance checklist as required by C14.4',
  'Final Text T10 completes C13 mobile parity without changing Table or desktop Text contracts',
  'Mobile Text Data now uses a compact summary and OPEN TEXT WORKSPACE full-height sheet, matching the desktop mini-entry to full-workspace pattern',
  'Mobile Text Library full workspace now receives move/delete Document and rename/delete Collection actions instead of silently omitting desktop CRUD capabilities',
  'Mobile Text Library/source/audio advanced tools remain available through the same TextLibraryShell contract, with 44px-class touch targets for workspace navigation and close actions',
  'Structured Text Player continues to open from the mobile bottom player into the shared responsive Text Player workspace; Text Batch continues through the dedicated structured Text Batch surface',
  'Final Text T9 polishes Legacy, Paragraph, and Conversation as three official Text paths before mobile parity',
  'Legacy desktop labels now describe pronunciation lines rather than structured Cards and the header shows LEGACY without the misleading MIXED compatibility prefix',
  'Paragraph gains Document-level Playback EN/ID and Edge Download EN/ID narrator defaults so a single narrator can be configured once for the whole Document',
  'Document playback/download defaults participate in the same inheritance resolver used by Player, manual audio, coverage, and Batch; Card/Segment overrides remain higher priority',
  'Conversation speaker input is required for new/edited Conversation Segments so speaker remains first-class data instead of silently creating anonymous dialogue lines',
  'Conversation compact Player summary now reports speaker count and Document fallback voices remain available below speaker-specific profiles',
  'Final Text T8 adds current-Document Card-range Batch scope while preserving permanent TEXT_ID/SEGMENT_ID identities and current EN/Text + ID/Meaning channel selection',
  'Conversation Text Batch keeps each Segment on its exact resolved speaker/channel Edge download voice; document speaker, Card speaker, and Segment overrides are not flattened to one Batch voice',
  'Text Batch coverage distinguishes Ready, history-only Downloaded, Other Voice, Stale, and Missing; only currently readable Staging/Folder/ZIP/runtime binary suppresses Download Missing',
  'Missing-only Text Batch resumes from mounted Staging, Folder, and ZIP coverage and skips already Ready exact variants without trusting export history',
  'Live Text Batch telemetry uses lightweight counters for Processed/Generated/Skipped Ready/Failed/Remaining/Ready estimate/Need estimate and publishes only at sparse UI checkpoints instead of rescanning IndexedDB per audio',
  'STOP keeps already committed partial binary valid and leaves the selected scope resumable through Download Missing on the next run',
  'Text Batch direct MP3 exports every Ready selected slot in browser-download waves of max 10 without starting TTS',
  'Text consolidated ZIP lazily combines Ready binaries across Text Staging, Folder, mounted ZIP, and runtime sources with a 64 MB resource ceiling; complete export is locked until Ready equals Total',
  'Explicit partial Text ZIP export remains available only as a clearly PARTIAL-labelled archive so incomplete coverage cannot be mistaken for a full package',
  'Canonical Text consolidated ZIP naming now supports PART_XX suffixes for resource-bounded multi-archive output while preserving compact resolved voice labels',
  'Final Text T7 makes manual Card/Segment audio exact-coverage aware: EN/Text and ID/Meaning show Ready/Missing status plus the resolved Edge download voice',
  'Card Audio adds Generate Missing, Regenerate All, STOP re-entry, per-Segment Generate/Regenerate, direct MP3 export, and complete-only CARD ZIP export without silent generation',
  'Manual MP3/CARD ZIP export reads the currently Ready binary lazily from Staging, Folder, ZIP, or runtime source and never treats history-only Downloaded metadata as exportable binary',
  'Card ZIP fails closed while any non-empty exact-voice slot is Missing so a partial archive cannot be mistaken for a complete Card package',
  'Manual Release removes Card-owned Staging binary while preserving core metadata/history; Folder/ZIP source-owned variants are protected from one-off Card deletion and manual local files remain removable',
  'Card Audio remains re-enterable during generation so STOP is reachable while playback controls stay protected from conflicting work',
  'Final Text T6 adds durable Text binary Staging in the shared Audio Staging database under an isolated text mode while keeping core Text IndexedDB v1 metadata-oriented',
  'Generated Text audio commits to Folder or Text Staging before runtime Blob release; large Batch packaging no longer retains thousands of generated Blobs/ObjectURLs in React/runtime memory',
  'Text Folder audio is indexed lazily and creates only on-demand ObjectURLs through a bounded cache; ZIP lazy behavior remains preserved',
  'Downloaded/export metadata is history only: only an actually accessible Staging/Folder/ZIP/runtime binary is Ready and can suppress missing-only generation',
  'Structured Text audio metadata upsert uses a segment/channel IndexedDB fast path instead of full Text Library getAll/diff work per generated audio',
  'Text Batch runtime/audio-variant React state is flushed periodically and browser ZIP packaging reads staged binary back in resource-bounded 64 MB groups',
  'Text Data exposes Clear Staging and Clear Runtime Cache controls; Text staging cache release is mode-scoped so it does not revoke Table staging ObjectURLs',
  'Desktop Text Workspace now renders through a document.body portal above the global player/header stacking contexts, fixing the remaining clipped/covered workspace path',
  'Final Text T5 introduces stable Conversation speaker identity in Segment metadata without changing Text IndexedDB v1 schema',
  'Document speaker playback profiles are active again for both EN/Text and ID/Meaning channels; Card speaker and Segment overrides remain higher priority',
  'Document speaker Edge download profiles are separate from playback voices and now participate in generation, coverage, runtime reconnect, and Card inheritance',
  'Card speaker playback/download overrides can bind to stable speaker IDs while legacy label-keyed profiles remain readable for backward compatibility',
  'Renaming a speaker label after its stable identity has been persisted no longer silently loses the intended Document speaker profile',
  'Final Text T4 moves persistent structured playback controls out of the learning/Card body and into a dedicated root Text Player workspace',
  'Bottom Audio Player now exposes TEXT PLAYER on desktop and Player on mobile while retaining play/pause/prev/next/stop transport',
  'Existing Show, playback channel order, Playback Feel, voice/audio download, generation, and source controls are preserved inside the Text Player workspace rather than removed',
  'Final Text T3 centralizes Text export/audio naming under one canonical filename domain; existing Table naming code remains untouched',
  'Generated Text audio now uses compact human voice tokens such as Ryan while retaining SEGMENT_ID + channel + engine + TXTAUDIO_ID identity in the filename',
  'Text Folder/ZIP reconnect accepts both legacy full voice tokens and the new compact voice token, so old exported audio remains reconnectable',
  'Text Pack JSON, Text DB Backup, and fallback browser Text audio ZIP names now use consistent double-underscore naming families and safe timestamps',
  'Final Text T2 implements canonical Text JSON Attach/Sync identity without changing the Text IndexedDB v1 object-store schema',
  'Repeated loading of the same canonical Text Pack now Syncs mapped local entities in place instead of silently creating another copy; Import as Copy preserves the old A14 independent-copy behavior explicitly',
  'Source attachment mapping, baseline fingerprints, status, last-sync metadata, and source filename metadata are persisted under the existing Text META store',
  'Sync creates new source entities with new permanent local IDs, updates clean mapped entities in place, removes clean source-owned entities deleted upstream, preserves local-only edits, and fails closed when the same mapped entity changed both locally and in source',
  'Detach • Keep Local removes the source relationship while preserving local content; Remove Source Data deletes only clean source-owned mapped content and refuses destructive removal when local edits or foreign local children exist',
  'Text Pack default package identity is stable across repeat exports and includes an immutable root creation stamp so unrelated databases with the same DOC/COLLECTION sequence do not collide accidentally',
  'Desktop Text Workspace is constrained to a bounded viewport with one internal vertical scroller and hidden horizontal overflow to fix the T1 workspace overflow path',
  'Document Move is exposed for local Documents so they can move between Library Root and Collections without changing permanent DOC_ID; attached source Documents must be detached before manual relocation',
  'Final Text T1 starts contract C0–C3 implementation without modifying frozen Table/R2 behavior',
  'Desktop Text Data sidebar is reduced to a compact summary with OPEN TEXT WORKSPACE; the full Text Library/editor/data stack moves to a root workspace overlay',
  'Legacy, Paragraph, and Conversation are official new-Document creation paths; Mixed remains compatibility-only and is not offered for new Documents',
  'Legacy can now be created as a first-class local Text Document for quick pronunciation/manual TTS experiments',
  'Document Delete is exposed in the Text Workspace with two-step confirmation and preserves permanent high-water identities',
  'Collection rename and empty-Collection deletion are exposed while non-empty Collection delete remains fail-closed',
  'A14 merge behavior is relabelled Import as Copy so duplicate semantics are explicit until C2 canonical Attach/Sync/Detach is implemented',
  'Live Batch Telemetry now updates lightweight processed/Ready estimate/Missing estimate/Generated/Skipped/Failed/Remaining counters without re-reading the full IndexedDB inventory',
  'Batch final reconciliation still refreshes authoritative IndexedDB-backed coverage at completion, stop, or safety checkpoint',
  'Exported* history no longer suppresses DOWNLOAD MISSING by itself: only a currently verified Staging/Folder/mounted-ZIP binary on the exact active voice is treated as Ready',
  'Mounted old ZIP coverage can therefore resume interrupted ranges without regenerating existing audio, while unavailable history-only slots are generated again',
  'Batch Workspace can build consolidated ZIP group(s) from a complete current selection by lazily combining Ready binaries across Staging, Folder, and mounted ZIP sources without TTS regeneration',
  'Consolidated ZIP stays locked while any selected slot is unavailable or wrong-voice, making incomplete audio coverage explicit before final archive export',
  'Large Table Batch runs now use a quiet per-audio path: binary staging continues per item while spinner/health/log/generated-meta/staging-array React updates are suppressed and staging/session UI is checkpointed at lower frequency',
  'Batch session bookkeeping now seeds Audio Staging metadata once and maintains an incremental metadata map instead of full IndexedDB getAll scans every 10 audio files',
  'ZIP safety chunk ceiling is reduced from 256 MB to 64 MB to lower peak renderer memory during auto-export',
  'Normal Edge/Gemini TTS success and expected client-abort logs are silent by default to prevent integrated-terminal scrollback growth during large Batch runs; TTS errors remain visible and PROLINGO_TTS_DEBUG=1 restores verbose TTS diagnostics',
  'Edge backend STOP/abort no longer destroys the msedge-tts stream; disconnected requests drain safely so Card/Batch/Text abort does not race the upstream WebSocket stream',
  'Batch direct MP3 export now exports every Ready audio in the current range/type/voice selection and throttles browser downloads in waves of max 10 instead of repeatedly taking only the first 10',
  'Card Audio now supports ALL MP3 and CARD ZIP export for all Ready child audio on the current EN/ID download voices without regenerating Missing audio',
  'Batch Library is now an inline show/hide section inside Batch Workspace with a three-session-height scroll box, avoiding nested popup stacking',
  'Batch Library history now shows book, range, voice, audio types, Ready/Staged/External/Unavailable and exported ZIP context; unavailable sessions disable export actions',
  'Batch ZIP filenames use compact voice names such as Ryan instead of full en-GB-RyanNeural identifiers',
  'The initial app workspace is Table again; Structured Text remains available but is no longer the startup tab',
  'Batch trigger now lives with Generate Engine/System & TTS and opens a root workspace overlay/bottom sheet instead of expanding inside the sidebar',
  'The lower System utility card now leaves Logs as the only standalone action, reducing sidebar height and keeping Batch re-entry independent from sidebar content',
  'Card Edit/Delete actions are locked while audio generation is active so destructive row changes cannot race an in-flight staged write',
  'Card-owned single-part generation now aborts on row unmount/virtualization just like Download All, preventing hidden orphan generation',
  'Batch Library no longer expands as a long list inside System/Batch; one Batch Library button shows the current-book history count and opens a dedicated history popup',
  'Batch now owns active-book/all-book Staging information and Clear Staging management, reducing duplicate storage UI in System controls',
  'Desktop and mobile System Batch buttons show the current-book Batch history count',
  'Per-card Audio can be reopened while manual generation is running; closing the panel no longer discards the visible Download All task state',
  'Per-card manual generation now has STOP for the current request and Download All sequence; Stop aborts the active TTS request and prevents the next Card item from starting',
  'Card Ready/Missing is resolved against the exact current System download voice, not whichever playback voice happens to be preferred',
  'Changing English download voice (for example Libby to Ryan) immediately makes missing Ryan slots downloadable while preserving the existing Libby variant; Indonesian voice behaves the same way',
  'Card MP3 export, staged Release, and replace detection use the same current download-voice identity so Folder/ZIP/Staging behavior stays consistent',
  'Card Download All remains staging-only and never inherits Batch Auto Export ZIP',
  'R2.3 exact VOCAB_ID audio scope and built-in Demo MASTER 1–5 remain included',
  'R2.2 LEARN OFF markers, R2.1 Settings hotfix, R2 Audio Staging/resource hardening, 10+10 Table overscan, and foreground playback snap remain included',
  'Structured Text feature development remains paused pending R2 runtime acceptance'
]);
