export const APP_VERSION = '5.14.7';
export const APP_VERSION_LABEL = `v${APP_VERSION}`;
export const APP_CHECKPOINT_ID = 'P4-TEXT-FINAL';
export const APP_CHECKPOINT_LABEL = 'P4-TEXT-FINAL • T8 C8+C9 — Text Batch Multi-Voice Resume & Consolidation';
export const APP_RELEASE_NAME = 'Final Text T8 Batch Multi-Voice Resume & Consolidation';
export const APP_RELEASE_DATE = '2026-09-18';

export const APP_READY_LOG = `Ready. ProLingo ${APP_VERSION_LABEL} (${APP_RELEASE_NAME}).`;
export const APP_DATA_MANAGER_RELEASE_NOTE = `${APP_VERSION_LABEL} Final Text T8: Text Batch now supports Card-range scope, exact multi-speaker/multi-voice coverage, lightweight live telemetry, resume from real Ready sources, direct MP3, and complete/explicit-partial consolidated ZIP export without re-generating Ready audio.`;
export const APP_MANUAL_EDITOR_RELEASE_LABEL = `${APP_VERSION_LABEL} • P4-TEXT-FINAL T8`;

export const APP_CHANGELOG = Object.freeze([
  'Final Text T8 adds current-Document Card-range Batch scope while preserving permanent TEXT_ID/SEGMENT_ID identities and current EN/Text + ID/Meaning channel selection',
  'Conversation Text Batch keeps each Segment on its exact resolved speaker/channel Edge download voice; document speaker, Card speaker, and Segment overrides are not flattened to one Batch voice',
  'Text Batch coverage distinguishes Ready, history-only Downloaded, Other Voice, Stale, and Missing; only currently readable Staging/Folder/ZIP/runtime binary suppresses Download Missing',
  'Missing-only Text Batch resumes from mounted Staging, Folder, and ZIP coverage and skips already Ready exact variants without trusting export history',
  'Live Text Batch telemetry uses lightweight counters for Processed/Generated/Skipped Ready/Failed/Remaining/Ready estimate/Need estimate and publishes only at sparse UI checkpoints instead of rescanning IndexedDB per audio',
  'STOP keeps already committed partial binary valid and leaves the selected scope resumable through Download Missing on the next run',
  'Text Batch direct MP3 exports every Ready selected slot in browser-download waves of max 10 without starting TTS',
  'Text consolidated ZIP lazily combines Ready binaries across Text Staging, Folder, mounted ZIP, and runtime sources with a 64 MB resource ceiling; complete export is locked until Ready equals Total',
  'Explicit partial Text ZIP export remains available only as a clearly PARTIAL-labelled archive so incomplete coverage cannot be mistaken for a full package',
  'Canonical Text consolidated ZIP naming now supports PART_XX suffixes for resource-bounded multi-archive output while preserving compact resolved voice labels',
  'Final Text T7 makes manual Card/Segment audio exact-coverage aware: EN/Text and ID/Meaning show Ready/Missing status plus the resolved Edge download voice',
  'Card Audio adds Generate Missing, Regenerate All, STOP re-entry, per-Segment Generate/Regenerate, direct MP3 export, and complete-only CARD ZIP export without silent generation',
  'Manual MP3/CARD ZIP export reads the currently Ready binary lazily from Staging, Folder, ZIP, or runtime source and never treats history-only Downloaded metadata as exportable binary',
  'Card ZIP fails closed while any non-empty exact-voice slot is Missing so a partial archive cannot be mistaken for a complete Card package',
  'Manual Release removes Card-owned Staging binary while preserving core metadata/history; Folder/ZIP source-owned variants are protected from one-off Card deletion and manual local files remain removable',
  'Card Audio remains re-enterable during generation so STOP is reachable while playback controls stay protected from conflicting work',
  'Final Text T6 adds durable Text binary Staging in the shared Audio Staging database under an isolated text mode while keeping core Text IndexedDB v1 metadata-oriented',
  'Generated Text audio commits to Folder or Text Staging before runtime Blob release; large Batch packaging no longer retains thousands of generated Blobs/ObjectURLs in React/runtime memory',
  'Text Folder audio is indexed lazily and creates only on-demand ObjectURLs through a bounded cache; ZIP lazy behavior remains preserved',
  'Downloaded/export metadata is history only: only an actually accessible Staging/Folder/ZIP/runtime binary is Ready and can suppress missing-only generation',
  'Structured Text audio metadata upsert uses a segment/channel IndexedDB fast path instead of full Text Library getAll/diff work per generated audio',
  'Text Batch runtime/audio-variant React state is flushed periodically and browser ZIP packaging reads staged binary back in resource-bounded 64 MB groups',
  'Text Data exposes Clear Staging and Clear Runtime Cache controls; Text staging cache release is mode-scoped so it does not revoke Table staging ObjectURLs',
  'Desktop Text Workspace now renders through a document.body portal above the global player/header stacking contexts, fixing the remaining clipped/covered workspace path',
  'Final Text T5 introduces stable Conversation speaker identity in Segment metadata without changing Text IndexedDB v1 schema',
  'Document speaker playback profiles are active again for both EN/Text and ID/Meaning channels; Card speaker and Segment overrides remain higher priority',
  'Document speaker Edge download profiles are separate from playback voices and now participate in generation, coverage, runtime reconnect, and Card inheritance',
  'Card speaker playback/download overrides can bind to stable speaker IDs while legacy label-keyed profiles remain readable for backward compatibility',
  'Renaming a speaker label after its stable identity has been persisted no longer silently loses the intended Document speaker profile',
  'Final Text T4 moves persistent structured playback controls out of the learning/Card body and into a dedicated root Text Player workspace',
  'Bottom Audio Player now exposes TEXT PLAYER on desktop and Player on mobile while retaining play/pause/prev/next/stop transport',
  'Existing Show, playback channel order, Playback Feel, voice/audio download, generation, and source controls are preserved inside the Text Player workspace rather than removed',
  'Final Text T3 centralizes Text export/audio naming under one canonical filename domain; existing Table naming code remains untouched',
  'Generated Text audio now uses compact human voice tokens such as Ryan while retaining SEGMENT_ID + channel + engine + TXTAUDIO_ID identity in the filename',
  'Text Folder/ZIP reconnect accepts both legacy full voice tokens and the new compact voice token, so old exported audio remains reconnectable',
  'Text Pack JSON, Text DB Backup, and fallback browser Text audio ZIP names now use consistent double-underscore naming families and safe timestamps',
  'Final Text T2 implements canonical Text JSON Attach/Sync identity without changing the Text IndexedDB v1 object-store schema',
  'Repeated loading of the same canonical Text Pack now Syncs mapped local entities in place instead of silently creating another copy; Import as Copy preserves the old A14 independent-copy behavior explicitly',
  'Source attachment mapping, baseline fingerprints, status, last-sync metadata, and source filename metadata are persisted under the existing Text META store',
  'Sync creates new source entities with new permanent local IDs, updates clean mapped entities in place, removes clean source-owned entities deleted upstream, preserves local-only edits, and fails closed when the same mapped entity changed both locally and in source',
  'Detach • Keep Local removes the source relationship while preserving local content; Remove Source Data deletes only clean source-owned mapped content and refuses destructive removal when local edits or foreign local children exist',
  'Text Pack default package identity is stable across repeat exports and includes an immutable root creation stamp so unrelated databases with the same DOC/COLLECTION sequence do not collide accidentally',
  'Desktop Text Workspace is constrained to a bounded viewport with one internal vertical scroller and hidden horizontal overflow to fix the T1 workspace overflow path',
  'Document Move is exposed for local Documents so they can move between Library Root and Collections without changing permanent DOC_ID; attached source Documents must be detached before manual relocation',
  'Final Text T1 starts contract C0–C3 implementation without modifying frozen Table/R2 behavior',
  'Desktop Text Data sidebar is reduced to a compact summary with OPEN TEXT WORKSPACE; the full Text Library/editor/data stack moves to a root workspace overlay',
  'Legacy, Paragraph, and Conversation are official new-Document creation paths; Mixed remains compatibility-only and is not offered for new Documents',
  'Legacy can now be created as a first-class local Text Document for quick pronunciation/manual TTS experiments',
  'Document Delete is exposed in the Text Workspace with two-step confirmation and preserves permanent high-water identities',
  'Collection rename and empty-Collection deletion are exposed while non-empty Collection delete remains fail-closed',
  'A14 merge behavior is relabelled Import as Copy so duplicate semantics are explicit until C2 canonical Attach/Sync/Detach is implemented',
  'Live Batch Telemetry now updates lightweight processed/Ready estimate/Missing estimate/Generated/Skipped/Failed/Remaining counters without re-reading the full IndexedDB inventory',
  'Batch final reconciliation still refreshes authoritative IndexedDB-backed coverage at completion, stop, or safety checkpoint',
  'Exported* history no longer suppresses DOWNLOAD MISSING by itself: only a currently verified Staging/Folder/mounted-ZIP binary on the exact active voice is treated as Ready',
  'Mounted old ZIP coverage can therefore resume interrupted ranges without regenerating existing audio, while unavailable history-only slots are generated again',
  'Batch Workspace can build consolidated ZIP group(s) from a complete current selection by lazily combining Ready binaries across Staging, Folder, and mounted ZIP sources without TTS regeneration',
  'Consolidated ZIP stays locked while any selected slot is unavailable or wrong-voice, making incomplete audio coverage explicit before final archive export',
  'Large Table Batch runs now use a quiet per-audio path: binary staging continues per item while spinner/health/log/generated-meta/staging-array React updates are suppressed and staging/session UI is checkpointed at lower frequency',
  'Batch session bookkeeping now seeds Audio Staging metadata once and maintains an incremental metadata map instead of full IndexedDB getAll scans every 10 audio files',
  'ZIP safety chunk ceiling is reduced from 256 MB to 64 MB to lower peak renderer memory during auto-export',
  'Normal Edge/Gemini TTS success and expected client-abort logs are silent by default to prevent integrated-terminal scrollback growth during large Batch runs; TTS errors remain visible and PROLINGO_TTS_DEBUG=1 restores verbose TTS diagnostics',
  'Edge backend STOP/abort no longer destroys the msedge-tts stream; disconnected requests drain safely so Card/Batch/Text abort does not race the upstream WebSocket stream',
  'Batch direct MP3 export now exports every Ready audio in the current range/type/voice selection and throttles browser downloads in waves of max 10 instead of repeatedly taking only the first 10',
  'Card Audio now supports ALL MP3 and CARD ZIP export for all Ready child audio on the current EN/ID download voices without regenerating Missing audio',
  'Batch Library is now an inline show/hide section inside Batch Workspace with a three-session-height scroll box, avoiding nested popup stacking',
  'Batch Library history now shows book, range, voice, audio types, Ready/Staged/External/Unavailable and exported ZIP context; unavailable sessions disable export actions',
  'Batch ZIP filenames use compact voice names such as Ryan instead of full en-GB-RyanNeural identifiers',
  'The initial app workspace is Table again; Structured Text remains available but is no longer the startup tab',
  'Batch trigger now lives with Generate Engine/System & TTS and opens a root workspace overlay/bottom sheet instead of expanding inside the sidebar',
  'The lower System utility card now leaves Logs as the only standalone action, reducing sidebar height and keeping Batch re-entry independent from sidebar content',
  'Card Edit/Delete actions are locked while audio generation is active so destructive row changes cannot race an in-flight staged write',
  'Card-owned single-part generation now aborts on row unmount/virtualization just like Download All, preventing hidden orphan generation',
  'Batch Library no longer expands as a long list inside System/Batch; one Batch Library button shows the current-book history count and opens a dedicated history popup',
  'Batch now owns active-book/all-book Staging information and Clear Staging management, reducing duplicate storage UI in System controls',
  'Desktop and mobile System Batch buttons show the current-book Batch history count',
  'Per-card Audio can be reopened while manual generation is running; closing the panel no longer discards the visible Download All task state',
  'Per-card manual generation now has STOP for the current request and Download All sequence; Stop aborts the active TTS request and prevents the next Card item from starting',
  'Card Ready/Missing is resolved against the exact current System download voice, not whichever playback voice happens to be preferred',
  'Changing English download voice (for example Libby to Ryan) immediately makes missing Ryan slots downloadable while preserving the existing Libby variant; Indonesian voice behaves the same way',
  'Card MP3 export, staged Release, and replace detection use the same current download-voice identity so Folder/ZIP/Staging behavior stays consistent',
  'Card Download All remains staging-only and never inherits Batch Auto Export ZIP',
  'R2.3 exact VOCAB_ID audio scope and built-in Demo MASTER 1–5 remain included',
  'R2.2 LEARN OFF markers, R2.1 Settings hotfix, R2 Audio Staging/resource hardening, 10+10 Table overscan, and foreground playback snap remain included',
  'Structured Text feature development remains paused pending R2 runtime acceptance'
]);
