import React from 'react';
import { Layers, Upload, X, FileDown, Database, Save, Trash2, Plus, ListPlus } from 'lucide-react';
import { V510_SOURCE_KEYS, V510_SOURCE_LABELS } from '../../constants/datasetConstants';

export default function MobileDataControls({
  mode, isMultiSourceMode, dirtySourceKeys, isSystemBusy, isCsvDirty, openFullPackPicker,
  sourceDiagnostics, sourceChangeSummaries, sourcePack, openSourcePicker, removeSourceLayer,
  saveUpdatedSource, exportMergedDataset, savedDecks, selectedDeckId, handleLoadDeck,
  currentDeckName, setCurrentDeckName, handleSaveDeck, handleDeleteDeckInit, csvInputRef,
  openManualAdd, playlist, tableViewMode, exportTableCSV, setIsClearDialogOpen, csvChangeSummary,
  setIsChangeReviewOpen, undoStack, undoLastDataChange, saveUpdatedCSV, rangeInput, setRangeInput,
  handleRangeAdd
}) {
  return (
    <>
              {mode === 'table' && <div className="bg-white dark:bg-slate-800 p-4 rounded-xl border border-violet-200 dark:border-violet-900 shadow-sm">
                  <div className="flex items-center justify-between mb-3"><h3 className="text-sm font-bold text-slate-800 dark:text-white flex items-center gap-2"><Layers className="w-4 h-4 text-violet-600"/> Source Manager</h3><span className={`text-[9px] font-black px-2 py-1 rounded ${isMultiSourceMode ? 'bg-violet-100 dark:bg-violet-900/30 text-violet-700 dark:text-violet-300' : 'bg-slate-100 dark:bg-slate-700 text-slate-500'}`}>{isMultiSourceMode ? `MULTI-SOURCE${dirtySourceKeys.length ? ` • ${dirtySourceKeys.length} DIRTY` : ''}` : 'FLAT'}</span></div>
                  <p className="text-[10px] text-slate-400 mb-3">MAIN owns VOCAB_ID + NO. Other files join by VOCAB_ID.</p>
                  <button disabled={isSystemBusy || isCsvDirty} onClick={openFullPackPicker} className="w-full mb-3 py-2 rounded-lg bg-violet-600 hover:bg-violet-700 text-white text-xs font-bold disabled:opacity-40"><Upload className="w-3.5 h-3.5 inline mr-1"/>Load Full Pack (Auto)</button>
                  <div className="space-y-2">{V510_SOURCE_KEYS.map(key => { const d = sourceDiagnostics[key]; const dirty = sourceChangeSummaries[key]; return <div key={key} className="rounded-lg border border-slate-200 dark:border-slate-700 p-2"><div className="flex items-center gap-2"><span className="w-16 text-[10px] font-black text-violet-600 dark:text-violet-400">{V510_SOURCE_LABELS[key]}</span><span className="flex-1 text-[9px] text-slate-400 truncate">{sourcePack[key]?.filename || 'Not loaded'}</span><button disabled={isSystemBusy} onClick={() => openSourcePicker(key)} className="px-2 py-1 text-[9px] font-bold border rounded dark:border-slate-600">{d.loaded ? 'Replace' : 'Load'}</button>{key !== 'main' && d.loaded && <button disabled={isSystemBusy || isCsvDirty} onClick={() => removeSourceLayer(key)} className="p-1 text-red-500"><X className="w-3 h-3"/></button>}</div>{d.loaded && <div className="mt-1 flex flex-wrap gap-1 text-[8px]"><span className="text-emerald-600">{d.rows} rows</span>{key !== 'main' && <><span className="text-slate-400">• {d.matched} matched</span>{d.missing > 0 && <span className="text-amber-600">• {d.missing} missing</span>}{d.orphan > 0 && <span className="text-red-500">• {d.orphan} orphan</span>}</>}{d.duplicates.length > 0 && <span className="text-red-500">• {d.duplicates.length} duplicate</span>}{dirty.isDirty && <button onClick={() => saveUpdatedSource(key)} className="ml-auto text-amber-700 dark:text-amber-300 font-bold">Save +{dirty.added} ~{dirty.modified} -{dirty.deleted}</button>}</div>}</div>; })}</div>
                  {isMultiSourceMode && <button onClick={exportMergedDataset} className="w-full mt-3 py-2 rounded border border-violet-200 dark:border-violet-800 text-violet-700 dark:text-violet-300 text-xs font-bold"><FileDown className="w-3.5 h-3.5 inline mr-1"/>Export Merged CSV</button>}
              </div>}

              <div className="bg-white dark:bg-slate-800 p-4 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm transition-colors">
                  <h3 className="text-sm font-bold text-slate-800 dark:text-white mb-3 flex items-center gap-2"><Database className="w-4 h-4"/> Deck & Data</h3>
                  <select disabled={isSystemBusy} className={`w-full text-xs p-2 border border-slate-200 dark:border-slate-600 rounded mb-2 bg-slate-50 dark:bg-slate-700 dark:text-white ${isSystemBusy ? 'opacity-50 cursor-not-allowed' : ''}`} onChange={handleLoadDeck} value={selectedDeckId}><option value="" disabled>Load Saved...</option>{Object.keys(savedDecks).map(name => <option key={name} value={name}>{name}</option>)}</select>
                  <div className="flex gap-2"><input disabled={isSystemBusy} className={`flex-1 border border-slate-200 dark:border-slate-600 rounded px-2 text-xs dark:bg-slate-700 dark:text-white ${isSystemBusy ? 'opacity-50 cursor-not-allowed' : ''}`} placeholder="Deck Name" value={currentDeckName} onChange={(e) => setCurrentDeckName(e.target.value)} /><button disabled={isSystemBusy} onClick={handleSaveDeck} title="Save Draft to Cache" className="p-2 bg-green-100 dark:bg-green-900/30 text-green-600 dark:text-green-400 rounded disabled:opacity-50"><Save className="w-4 h-4"/></button>{selectedDeckId && <button disabled={isSystemBusy} onClick={handleDeleteDeckInit} className="p-2 bg-red-100 dark:bg-red-900/30 text-red-600 dark:text-red-400 rounded disabled:opacity-50"><Trash2 className="w-4 h-4"/></button>}</div>
                  {mode === 'table' && <div className="mt-3 space-y-2">
                      <div className="grid grid-cols-2 gap-2"><button disabled={isSystemBusy} onClick={() => csvInputRef.current?.click()} className="flex items-center justify-center gap-1 px-3 py-2 rounded text-xs font-bold border border-slate-200 dark:border-slate-600 text-slate-600 dark:text-slate-300 disabled:opacity-50"><Upload className="w-3.5 h-3.5"/> Import CSV</button><button disabled={isSystemBusy} onClick={openManualAdd} className="flex items-center justify-center gap-1 px-3 py-2 rounded text-xs font-bold bg-indigo-600 text-white disabled:opacity-50"><Plus className="w-3.5 h-3.5"/> Add Manual</button></div>
                      <div className="grid grid-cols-2 gap-2"><button disabled={isSystemBusy || playlist.filter(i => i.isStructured).length === 0} onClick={() => exportTableCSV(tableViewMode === 'study' ? 'study' : 'master')} className="flex items-center justify-center gap-1 px-3 py-2 rounded text-xs font-bold border border-slate-200 dark:border-slate-600 text-slate-600 dark:text-slate-300 disabled:opacity-50"><FileDown className="w-3.5 h-3.5"/> Export Copy</button><button disabled={isSystemBusy} onClick={() => setIsClearDialogOpen(true)} className="flex items-center justify-center gap-1 px-3 py-2 rounded text-xs font-bold border border-red-100 dark:border-red-900/50 text-red-500 disabled:opacity-50"><Trash2 className="w-3.5 h-3.5"/> Clear View</button></div>
                      <div className={`px-3 py-2 rounded-lg border text-[10px] font-bold ${isCsvDirty ? 'bg-amber-50 border-amber-200 text-amber-700 dark:bg-amber-900/20 dark:border-amber-800 dark:text-amber-300' : 'bg-emerald-50 border-emerald-200 text-emerald-700 dark:bg-emerald-900/20 dark:border-emerald-800 dark:text-emerald-300'}`}>{isCsvDirty ? `Unsaved CSV • +${csvChangeSummary.added} new • ~${csvChangeSummary.modified} edited • -${csvChangeSummary.deleted} deleted` : 'CSV synced with last saved snapshot'}</div>
                      <div className="grid grid-cols-2 gap-2"><button disabled={!isCsvDirty} onClick={() => setIsChangeReviewOpen(true)} className="px-3 py-2 rounded text-xs font-bold border border-amber-200 dark:border-amber-800 text-amber-700 dark:text-amber-300 disabled:opacity-50">Review</button><button disabled={!undoStack.length} onClick={undoLastDataChange} className="px-3 py-2 rounded text-xs font-bold border border-indigo-200 dark:border-indigo-800 text-indigo-600 dark:text-indigo-400 disabled:opacity-50">Undo</button></div>
                      <button disabled={isSystemBusy || !isCsvDirty} onClick={saveUpdatedCSV} className={`w-full px-3 py-2 rounded text-xs font-bold ${isCsvDirty ? 'bg-amber-600 hover:bg-amber-700 text-white' : 'bg-slate-100 dark:bg-slate-700 text-slate-400'} disabled:opacity-60`}>{isMultiSourceMode ? 'Export Merged CSV' : 'Save Updated CSV'}</button>
                  </div>}
              </div>

              {mode === 'table' && <div className="bg-white dark:bg-slate-800 p-4 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm transition-colors"><h3 className="text-sm font-bold text-slate-800 dark:text-white mb-3 flex items-center gap-2"><ListPlus className="w-4 h-4 text-indigo-600 dark:text-indigo-400"/> Add to Queue (Range)</h3><div className="flex gap-2"><input className="flex-1 text-sm border border-slate-300 dark:border-slate-600 rounded px-3 py-2 focus:outline-indigo-500 dark:bg-slate-700 dark:text-white" placeholder="Ex: 1-10, 15" value={rangeInput} onChange={(e) => setRangeInput(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && handleRangeAdd()} disabled={isSystemBusy}/><button onClick={handleRangeAdd} disabled={!rangeInput.trim() || isSystemBusy} className={`px-4 py-2 rounded text-xs font-bold ${!rangeInput.trim() || isSystemBusy ? 'bg-slate-100 dark:bg-slate-700 text-slate-400' : 'bg-indigo-600 text-white'}`}>Apply</button></div></div>}
    </>
  );
}
